name: garfield-dev-team/aliyun-oss-action
description: "Aliyun OSS Action"
inputs:
  endpoint:
    description: "Override action name, the default name is the package name."
    required: true
  bucket:
    description: "Override action name, the default name is the package name."
    required: true
  ACCESS_KEY_ID:
    description: "Github token for PR comments. Optional."
    required: true
  ACCESS_KEY_SECRET:
    description: "Github token for PR comments. Optional."
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    ACCESS_KEY_ID: "${{ inputs.ACCESS_KEY_ID }}"
    ACCESS_KEY_SECRET: "${{ inputs.ACCESS_KEY_SECRET }}"
  args:
    - "-endpoint=${{ inputs.endpoint }}"
    - "-bucket=${{ inputs.bucket }}"

branding:
  icon: activity
  color: blue
