name: garfield-dev-team/aliyun-oss-action
description: "Aliyun OSS Action"
inputs:
  endpoint:
    description: "填写Bucket对应的Endpoint"
    required: true
  bucket:
    description: "填写存储空间名称"
    required: true
  ACCESS_KEY_ID:
    description: "填写阿里云账号AccessKey"
    required: true
  ACCESS_KEY_SECRET:
    description: "填写阿里云账号AccessKeySecret"
    required: true

runs:
  using: docker
  image: Dockerfile
  env:
    ACCESS_KEY_ID: "${{ inputs.ACCESS_KEY_ID }}"
    ACCESS_KEY_SECRET: "${{ inputs.ACCESS_KEY_SECRET }}"
  args:
    - "-endpoint=${{ inputs.endpoint }}"
    - "-bucket=${{ inputs.bucket }}"

branding:
  icon: activity
  color: blue
